### ISSUE TITLE
DeepSpCas9 on-target scoring throws an error libgfortran.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Omdeno** [crisprVerse/crisprScore#19]
Hi, thanks for the great tools for gRNA design! I had a problem with DeepSpCas9 on-target scoring. The function addOnTargetScores(guideSet, methods = c("deepspcas9")) gave this error:
 ```
Traceback (most recent call last):
  File "/disk1/domelchenko/projects/gRNA_DB_Bnapus/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/crisprScore/python/deepspcas9/getDeepSpCas9Scores.py", line 8, in <module>
    import tensorflow as tf
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libgfortran.so.3: cannot open shared object file: No such file or directory

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/tmp/Rtmpq0zQDQ/output.txt': No such file or directory
```

In case anyone else encounters this error, the solution was to install libgcc=7.2.0 in the deepspcas9__basilisk conda environment to change libgfortran.so.5 to libgfortran.so.3 in the libs directory.

```
source /home/d_omelchenko/.cache/R/basilisk/1.18.0/0/bin/activate
conda activate /home/d_omelchenko/.cache/R/basilisk/1.18.0/crisprScore/1.10.0/deepspcas9__basilisk
conda install -c conda-forge libgcc=7.2.0
```

Perhaps the `libgcc=7.2.0` specification should be added to the `deepspcas9_dependencies` in the [basilisk.R](https://github.com/crisprVerse/crisprScore/blob/d1a68f6c2522d752da892d71be76fbb3adf1558a/R/basilisk.R) file.

```
sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Europe/Moscow
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] basilisk.utils_1.18.0  basilisk_1.18.0        reticulate_1.39.0      GenomicFeatures_1.58.0 AnnotationDbi_1.68.0   Biobase_2.66.0        
 [7] crisprDesign_1.8.0     crisprScore_1.10.0     crisprScoreData_1.10.0 ExperimentHub_2.14.0   AnnotationHub_3.14.0   BiocFileCache_2.14.0  
[13] dbplyr_2.5.0           crisprBase_1.10.0      BSgenome.FescKK8_4.0   BSgenome_1.74.0        rtracklayer_1.66.0     BiocIO_1.16.0         
[19] Biostrings_2.74.0      XVector_0.46.0         GenomicRanges_1.58.0   GenomeInfoDb_1.42.0    IRanges_2.40.0         S4Vectors_0.44.0      
[25] BiocGenerics_0.52.0   

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.1            dplyr_1.1.4                 blob_1.2.4                  filelock_1.0.3              bitops_1.0-9               
 [6] fastmap_1.2.0               RCurl_1.98-1.16             VariantAnnotation_1.52.0    GenomicAlignments_1.42.0    digest_0.6.37              
[11] XML_3.99-0.17               lifecycle_1.0.4             KEGGREST_1.46.0             RSQLite_2.3.7               magrittr_2.0.3             
[16] compiler_4.4.1              progress_1.2.3              rlang_1.1.4                 tools_4.4.1                 utf8_1.2.4                 
[21] yaml_2.3.10                 prettyunits_1.2.0           S4Arrays_1.6.0              bit_4.5.0                   curl_5.2.3                 
[26] DelayedArray_0.32.0         xml2_1.3.6                  abind_1.4-8                 BiocParallel_1.40.0         withr_3.0.2                
[31] txdbmaker_1.2.0             grid_4.4.1                  fansi_1.0.6                 biomaRt_2.62.0              SummarizedExperiment_1.36.0
[36] cli_3.6.3                   crayon_1.5.3                generics_0.1.3              rstudioapi_0.17.1           Rbowtie_1.46.0             
[41] httr_1.4.7                  tzdb_0.4.0                  rjson_0.2.23                DBI_1.2.3                   cachem_1.1.0               
[46] stringr_1.5.1               zlibbioc_1.52.0             parallel_4.4.1              BiocManager_1.30.25         restfulr_0.0.15            
[51] matrixStats_1.4.1           vctrs_0.6.5                 Matrix_1.7-1                dir.expiry_1.14.0           jsonlite_1.8.9             
[56] hms_1.1.3                   bit64_4.5.2                 crisprBowtie_1.10.0         glue_1.8.0                  codetools_0.2-20           
[61] stringi_1.8.4               BiocVersion_3.20.0          UCSC.utils_1.2.0            tibble_3.2.1                pillar_1.9.0               
[66] rappdirs_0.3.3              randomForest_4.7-1.2        GenomeInfoDbData_1.2.13     httr2_1.0.5                 R6_2.5.1                   
[71] lattice_0.22-6              readr_2.1.5                 png_0.1-8                   Rsamtools_2.22.0            memoise_2.0.1              
[76] renv_1.0.11                 Rcpp_1.0.13-1               SparseArray_1.6.0           MatrixGenerics_1.18.0       pkgconfig_2.0.3          
```

**Comment by ericmalekos** [comment]
I also had dependency issues on DeepSpCas9, I removed the basilisk env and installed in this way:

```
conda env remove --prefix /home/eric/.cache/R/basilisk/1.20.0/crisprScore/1.12.0/deepspcas9__basilisk

/home/eric/.cache/R/basilisk/1.20.0/0/bin/conda create --yes \
    --prefix /home/eric/.cache/R/basilisk/1.20.0/crisprScore/1.12.0/deepspcas9__basilisk \
    -c bioconda -c conda-forge --override-channels \
    'python=2.7' 'scipy=1.1.0' 'numpy=1.14.5' \
    'libgfortran=3.0.0=1' \
    'pip<20' 'setuptools<50' 'wheel<0.35'

/home/eric/.cache/R/basilisk/1.20.0/crisprScore/1.12.0/deepspcas9__basilisk/bin/pip install tensorflow==1.4.1
```

of course `/home/eric/...` should be updated to whatever the installation path is

This worked in Ubuntu

**Comment by Jfortin1** [comment]
Hi @ericmalekos @Omdeno, I'm going to spend the next few weeks fixing crisprScore, this is super useful. It's been quite a journey to adapt to conda and reticulate and basilisk over the years, so much revamping is needed.

**Comment by Jfortin1** [comment]
@ericmalekos @Omdeno DeepSpCas9 and other python2 environments are no longer supported by crisprScore moving forward. See vignette in https://github.com/crisprVerse/crisprScore/tree/noBasilisk
